// Project.Api\Modules\Applicants\Models\Dto\AbitExamInfoDto.cs
namespace Project.Api.Modules.Applicants.Models.Dto
{
    public class AbitExamInfoDto
    {
        public int Id { get; set; }
        public int ApplicationCode { get; set; }
        public double? BallTotal { get; set; }
        public int? InCompetition { get; set; }
        public double? Score1 { get; set; }
        public double? Score2 { get; set; }
        public double? Score3 { get; set; }
        public double? Score4 { get; set; }
        public double? Score5 { get; set; }
        public double? Score6 { get; set; }
        public double? Total { get; set; }
        public double? AdditionalScoreId { get; set; }
        public double? ScoreSum { get; set; }
        public string? Exam1 { get; set; }
        public string? Exam2 { get; set; }
        public string? Exam3 { get; set; }
        public string? Exam4 { get; set; }
        public string? Exam5 { get; set; }
        public string? Exam6 { get; set; }
        public string? Disc1 { get; set; }
        public string? Disc2 { get; set; }
        public string? Disc3 { get; set; }
        public string? Disc4 { get; set; }
        public string? Disc5 { get; set; }
        public string? Disc6 { get; set; }
        public int? DiscCode1 { get; set; }
        public int? DiscCode2 { get; set; }
        public int? DiscCode3 { get; set; }
        public int? DiscCode4 { get; set; }
        public int? DiscCode5 { get; set; }
        public int? DiscCode6 { get; set; }
        public double? Mat { get; set; }
        public double? Ikt { get; set; }
        public double? Fiz { get; set; }
        public double? Rus { get; set; }
        public double? Him { get; set; }
        public double? Ist { get; set; }
        public double? Obsh { get; set; }
        public double? Ris { get; set; }
        public double? Lit { get; set; }
        public double? Komp { get; set; }
        public double? InYaz { get; set; }
        public double? Geo { get; set; }
        public double? Bio { get; set; }
        public double? TI { get; set; }
        public string? RusExam { get; set; }
        public string? MatExam { get; set; }
        public string? ObshExam { get; set; }
        public string? FizExam { get; set; }
        public string? HimExam { get; set; }
        public string? BioExam { get; set; }
        public string? GeoExam { get; set; }
        public string? IstExam { get; set; }
        public string? IktExam { get; set; }
        public double? AvgTotal { get; set; }
        public double? AvgEge { get; set; }
        public double? AvgVi { get; set; }
        public double? MinEgeScore { get; set; }
        public DateTime? Date1 { get; set; }
        public DateTime? Date2 { get; set; }
        public DateTime? Date3 { get; set; }
        public DateTime? Date4 { get; set; }
        public DateTime? Date5 { get; set; }
        public DateTime? Date6 { get; set; }
        public double? AdditionalScoreNoEssay { get; set; }
        public double? EssayScore { get; set; }
        public double? IdWeight { get; set; }
        public int? SpecialtyCode { get; set; }
        public bool? Z { get; set; }
        public int? U { get; set; }
        public bool? Agreement { get; set; }
        public int? Ege { get; set; }
        public int? NoEge { get; set; }
        public double? MinScore { get; set; }
        public int? Admission { get; set; }
        public int? Admission1 { get; set; }
        public int? Admission2 { get; set; }
        public int? Admission3 { get; set; }
        public int? Admission4 { get; set; }
        public int? Admission5 { get; set; }
        public int? Admission6 { get; set; }
        public int? Olim100 { get; set; }
    }
}